index:
    path:     /
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Page:index }


page_about:
    path: /about
    defaults: {_controller: AlbumReviewAlbumReviewBundle:Page:about }
    requirements:
        _method: GET
