api_album:
  type: rest
  resource: AlbumReview\AlbumReviewBundle\Controller\AlbumReviewAPIController
  name_prefix: api_album_
  prefix: /

api_user_album_review:
  type: rest
  resource: AlbumReview\AlbumReviewBundle\Controller\UserAlbumReviewAPIController
  name_prefix: api_user_album_review_
  prefix: /

api_token:
  type: rest
  resource: AlbumReview\AlbumReviewBundle\Controller\TokenAPIController
  name_prefix: api_token_
  prefix: /
