index:
    path: /
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Page:index }

page_about:
    path: /about
    defaults: {_controller: AlbumReviewAlbumReviewBundle:Page:about }
    requirements:
        _method: GET

album_view:
    path:     /view/{id}
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Album:view }
    requirements:
        id: \d+

album_search:
    path: /search
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Album:handleSearch }
    requirements:
        _method: POST

album_create:
    path:     /create
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Album:create }

album_edit:
    path:     /edit/{id}
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Album:edit }
    requirements:
        id: \d+

album_delete:
    path:     /delete/{id}
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Album:delete }
    requirements:
        id: \d+

create_review:
    path:     /createReview
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Review:createReview }

edit_review:
    path:     /editReview/{id}
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Review:editReview }

delete_review:
    path:     /deleteReview/{id}
    defaults: { _controller: AlbumReviewAlbumReviewBundle:Review:deleteReview }
