album_review_album_review:
    resource: "@AlbumReviewAlbumReviewBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AlbumReviewAlbumReviewBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



