<?php

namespace AlbumReview\AlbumReviewBundle\Repository;

/**
 * AlbumEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
