<?php

namespace AlbumReview\AlbumReviewBundle\Repository;

/**
 * ReviewEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
