<?php

namespace AlbumReview\AlbumReviewBundle\Repository;

/**
 * ReviewEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewEntryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $album_id
     * @return mixed
     */
    public function getAssociatedReviews($album_id)
    {
        //Get all the reviews that are associated with the album id.
        //Get reviews from review.entry where album_id is equal to the
        //the current album
        $queryBuilder = $this->createQueryBuilder('entry');
        $queryBuilder->orderBy('entry.id', 'DESC')
            ->setParameter(':albumID', $album_id)
            ->where('entry.album = :albumID');
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
