<?php

namespace AlbumReview\AlbumReviewBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserSpecificReviews($username){
        $queryBuilder = $this->createQueryBuilder('user');
        $queryBuilder->select('user')
            ->setParameter(':username', $username)
            ->where('user.username = :username')
            ->andWhere('review.album = :albumid');
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
